version: '3'
services:
  nginx:
    build: ./docker/nginx
    container_name: simple_catalog_nginx
    depends_on:
      - php
    environment:
      NGINX_HOST: test.io
      NGINX_PORT: 80
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  php:
    build: ./docker/php
    container_name: simple_catalog_php
    environment:
      NGINX_RUN_USER: "user"
    expose:
      - "9000"
    networks:
      - internal
    user: "user"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php.d/www.conf
    working_dir: "/var/www/html"

  node:
    build: ./docker/node
    command: tail -f /dev/null
    container_name: simple_catalog_node
    networks:
      - internal
    user: "node"
    volumes:
      - ./:/var/www/html
    working_dir: "/var/www/html"

  mysql:
    build: ./docker/mysql
    container_name: simple_catalog_mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal
    ports:
      - "3306:3306"

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.1/24
